//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThermoCtripLogin
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_Employees
    {
        public int ID { get; set; }
        public string CompanyNo { get; set; }
        public string Division { get; set; }
        public string Department { get; set; }
        public string StaffCode { get; set; }
        public string StaffNameCN { get; set; }
        public string StaffNameEN { get; set; }
        public string CostCenter { get; set; }
        public string WorkCenter { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Inner_Email { get; set; }
        public string Exter_Email { get; set; }
        public string iVantage_Code { get; set; }
        public string Manager { get; set; }
        public string ManagerName { get; set; }
        public string ADAccount { get; set; }
        public string Manual { get; set; }
        public string IsCLT { get; set; }
        public string IsPersident { get; set; }
        public Nullable<double> CashAdvance { get; set; }
        public string ExtendInfo1 { get; set; }
        public string ExtendInfo2 { get; set; }
        public string ExtendInfo3 { get; set; }
        public string ExtendInfo4 { get; set; }
        public string ExtendInfo5 { get; set; }
        public string ExtendInfo6 { get; set; }
        public string ExtendInfo7 { get; set; }
        public string ExtendInfo8 { get; set; }
        public string ExtendInfo9 { get; set; }
        public string ExtendInfo10 { get; set; }
        public Nullable<System.DateTime> EmployDate { get; set; }
        public Nullable<System.DateTime> DimissionDate { get; set; }
        public string EmployeeType { get; set; }
        public Nullable<System.DateTime> ProbationDate { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public Nullable<System.DateTime> LastContractDate { get; set; }
        public string BusinessUnit { get; set; }
        public string Band { get; set; }
        public string Temp { get; set; }
        public string Intern { get; set; }
        public string KingDee1 { get; set; }
        public string KingDee2 { get; set; }
        public string KingDee3 { get; set; }
        public string KingDee4 { get; set; }
        public string KingDee5 { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> ISExceptionMan { get; set; }
        public string CityRayManager { get; set; }
        public string TeamStaffCode { get; set; }
        public string TeamStaffName { get; set; }
        public string HRBPStaffAD { get; set; }
        public string Group { get; set; }
        public string JobFamily { get; set; }
        public string Track { get; set; }
    }
}
